// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MyFinanceNote.Models;

public partial class Tayra
{
    [Key]
    public int Id { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime Date { get; set; }

    [Required]
    [Column(TypeName = "ntext")]
    public string Event { get; set; }

    [Column(TypeName = "money")]
    public decimal Cash { get; set; }

    [Column(TypeName = "money")]
    public decimal Icoca { get; set; }

    [Column(TypeName = "money")]
    public decimal Coop { get; set; }
}