// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MyFinanceNote.Models;

public partial class Tayra : IComparable<Tayra>
{
    [Key]
    public int Id { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime Date { get; set; } = DateTime.Now;

    [Required]
    [Column(TypeName = "ntext")]
    public string Event { get; set; } = string.Empty;

    [Column(TypeName = "decimal(18,0)")]
    public decimal Cash { get; set; } = 0;

    [Column(TypeName = "decimal(18,0)")]
    public decimal Icoca { get; set; } = decimal.Zero;

    [Column(TypeName = "decimal(18,0)")]
    public decimal Coop { get; set; } = decimal.Zero;

    public int CompareTo(Tayra other)
    {
        if (this == other) return 0;
        if (other == null) return 1;
        if (this.Date  < other.Date) return -1;
        if (this.Date > other.Date) return 1;
        if (this.Date == other.Date)
        {
            return Id.CompareTo(other.Id);
        }
        return 0;
    }
}